<?php
namespace ILAB_Aws\IoTAnalytics;

use ILAB_Aws\AwsClient;

/**
 * This client is used to interact with the **AWS IoT Analytics** service.
 * @method \ILAB_Aws\Result batchPutMessage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise batchPutMessageAsync(array $args = [])
 * @method \ILAB_Aws\Result cancelPipelineReprocessing(array $args = [])
 * @method \GuzzleHttp\Promise\Promise cancelPipelineReprocessingAsync(array $args = [])
 * @method \ILAB_Aws\Result createChannel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createChannelAsync(array $args = [])
 * @method \ILAB_Aws\Result createDataset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createDatasetAsync(array $args = [])
 * @method \ILAB_Aws\Result createDatasetContent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createDatasetContentAsync(array $args = [])
 * @method \ILAB_Aws\Result createDatastore(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createDatastoreAsync(array $args = [])
 * @method \ILAB_Aws\Result createPipeline(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createPipelineAsync(array $args = [])
 * @method \ILAB_Aws\Result deleteChannel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteChannelAsync(array $args = [])
 * @method \ILAB_Aws\Result deleteDataset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteDatasetAsync(array $args = [])
 * @method \ILAB_Aws\Result deleteDatasetContent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteDatasetContentAsync(array $args = [])
 * @method \ILAB_Aws\Result deleteDatastore(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteDatastoreAsync(array $args = [])
 * @method \ILAB_Aws\Result deletePipeline(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deletePipelineAsync(array $args = [])
 * @method \ILAB_Aws\Result describeChannel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeChannelAsync(array $args = [])
 * @method \ILAB_Aws\Result describeDataset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeDatasetAsync(array $args = [])
 * @method \ILAB_Aws\Result describeDatastore(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeDatastoreAsync(array $args = [])
 * @method \ILAB_Aws\Result describeLoggingOptions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeLoggingOptionsAsync(array $args = [])
 * @method \ILAB_Aws\Result describePipeline(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describePipelineAsync(array $args = [])
 * @method \ILAB_Aws\Result getDatasetContent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getDatasetContentAsync(array $args = [])
 * @method \ILAB_Aws\Result listChannels(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listChannelsAsync(array $args = [])
 * @method \ILAB_Aws\Result listDatasetContents(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDatasetContentsAsync(array $args = [])
 * @method \ILAB_Aws\Result listDatasets(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDatasetsAsync(array $args = [])
 * @method \ILAB_Aws\Result listDatastores(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDatastoresAsync(array $args = [])
 * @method \ILAB_Aws\Result listPipelines(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listPipelinesAsync(array $args = [])
 * @method \ILAB_Aws\Result listTagsForResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTagsForResourceAsync(array $args = [])
 * @method \ILAB_Aws\Result putLoggingOptions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise putLoggingOptionsAsync(array $args = [])
 * @method \ILAB_Aws\Result runPipelineActivity(array $args = [])
 * @method \GuzzleHttp\Promise\Promise runPipelineActivityAsync(array $args = [])
 * @method \ILAB_Aws\Result sampleChannelData(array $args = [])
 * @method \GuzzleHttp\Promise\Promise sampleChannelDataAsync(array $args = [])
 * @method \ILAB_Aws\Result startPipelineReprocessing(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startPipelineReprocessingAsync(array $args = [])
 * @method \ILAB_Aws\Result tagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise tagResourceAsync(array $args = [])
 * @method \ILAB_Aws\Result untagResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise untagResourceAsync(array $args = [])
 * @method \ILAB_Aws\Result updateChannel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateChannelAsync(array $args = [])
 * @method \ILAB_Aws\Result updateDataset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateDatasetAsync(array $args = [])
 * @method \ILAB_Aws\Result updateDatastore(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateDatastoreAsync(array $args = [])
 * @method \ILAB_Aws\Result updatePipeline(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updatePipelineAsync(array $args = [])
 */
class IoTAnalyticsClient extends AwsClient {}
